### ISSUE TITLE
Add DNF package manager

### ISSUE THREAD

**Issue by CleanMachine1** [Crilum/update#10]
Fedora Linux uses DNF

See https://docs.fedoraproject.org/en-US/quick-docs/dnf/ for some docs
however to update is `sudo dnf upgrade`

**Comment by Crilum** [comment]
Hey @CleanMachine1!

Do you use Fedora? I have no experience with it, and so I have no idea how to use `dnf`, however, I have actually been thinking about adding support for more package managers, so I am totally open to adding this functionality. Is `sudo dnf upgrade` eqivalent to `suod apt update && sudo apt upgrade`?

**Comment by CleanMachine1** [comment]
I started yesterday since I had an ssd to fill, from what I can tell, sudo dnf upgrade == sudo apt update && sudo apt full-upgrade

**Comment by Crilum** [comment]
Hey, can `dnf` update itself like this: `sudo dnf upgrade dnf`? I can't test it, but I don't want to exclude the dnf package by removing it if it's used as the update argument

**Comment by Crilum** [comment]
Alright, I've added dnf in the latest commits, can you test it? Just like this:
```bash
cd /tmp
wget -q https://github.com/Crilum/update/raw/main/update
./update dnf
```

**Comment by CleanMachine1** [comment]
I don't particuallary understand these lines 
pkgs="$*"
if [[ "$pkgs" =~ "--no-grep-args" ]]; then
    pkgs="$(echo $pkgs | sed -e 's/--no-grep-args//g' -e 's/--all//g' -e 's/-a//g' -e 's/--apt//g' -e 's/-A//g' -e 's/all//g' -e 's/--npm//g' -e 's/-n//g' -e 's/snaps//g' -e 's/-s//g' -e 's/--snaps//g' -e 's/-f//g' -e 's/--flatpak//g' -e 's/-d//g' -e 's/--dnf//g')"
else
    pkgs="$(echo $pkgs | sed -e 's/--no-grep-args//g' -e 's/--all//g' -e 's/-a//g' -e 's/--apt//g' -e 's/apt//g' -e 's/-A//g' -e 's/all//g' -e 's/npm//g' -e 's/--npm//g' -e 's/-n//g' -e 's/snaps//g' -e 's/-s//g' -e 's/--snaps//g' -e 's/flatpak//g' -e 's/-f//g' -e 's/--flatpak//g' -e 's/dnf//g' -e 's/-d//g' -e 's/--dnf//g')"
fi

**Comment by CleanMachine1** [comment]
./update: line 166: upd_upd_script: command not found

Welcome to Crilum's Update Script!
Last metadata expiration check: 0:16:24 ago
Dependencies resolved.
Nothing to do.
Complete!

I feared that it would try to mess about with Pi-Apps so I removed everything but what was needed.

**Comment by Crilum** [comment]
Ok, thanks. 

>./update: line 166: upd_upd_script: command not found

`./update: line 166: upd_upd_script: command not found` is because you removed the self-updater function, don't worry about that.

>I feared that it would try to mess about with Pi-Apps so I removed everything but what was needed.

If you have Pi-Apps installed, `update` should only run `~/pi-apps/updater cli-yes`. 

>I don't particuallary understand these lines
```bash
pkgs="$*"
if [[ "$pkgs" =~ "--no-grep-args" ]]; then
pkgs="$(echo $pkgs | sed -e 's/--no-grep-args//g' -e 's/--all//g' -e 's/-a//g' -e 's/--apt//g' -e 's/-A//g' -e 's/all//g' -e 's/--npm//g' -e 's/-n//g' -e 's/snaps//g' -e 's/-s//g' -e 's/--snaps//g' -e 's/-f//g' -e 's/--flatpak//g' -e 's/-d//g' -e 's/--dnf//g')"
else
pkgs="$(echo $pkgs | sed -e 's/--no-grep-args//g' -e 's/--all//g' -e 's/-a//g' -e 's/--apt//g' -e 's/apt//g' -e 's/-A//g' -e 's/all//g' -e 's/npm//g' -e 's/--npm//g' -e 's/-n//g' -e 's/snaps//g' -e 's/-s//g' -e 's/--snaps//g' -e 's/flatpak//g' -e 's/-f//g' -e 's/--flatpak//g' -e 's/dnf//g' -e 's/-d//g' -e 's/--dnf//g')"
fi
```

This code removes arguments from the package list (`$pkgs`), so you can specify specific packages to update.
If you specify `--no-grep-args`, and are updating apps from apt, like this: `update apt yad`, say, the equivalent command would be:  `sudo apt update && sudo apt upgrade apt yad`.
If you didn't specify `--no-grep-args`, it would be this: `sudo apt update && sudo apt upgrade yad`.

@CleanMachine1 Thanks for testing for me! I'll make a release.
