### ISSUE TITLE
Pacman -Syyu

### ISSUE THREAD

**Issue by CleanMachine1** [Crilum/update#11]
-Syyu should NOT be used unless there is a reason for it.

Use `sudo pacman -Syu`

[Explicit Explanation ](https://gist.github.com/Brottweiler/952c8b0de0afc01c6c8ef18b5a1a5294)

It forces the server to fetch the package lists fully, putting strain on the servers

**Comment by Crilum** [comment]
Thanks, I've only really used Arch (well, it was actually Manjaro, but whatever) for a day, so I'm not super pacman litterate.

I'll change this.

**Comment by Crilum** [comment]
I've changed this in my latest commits, just waiting on your confirmation in #10.

**Comment by Crilum** [comment]
> [Explicit Explanation ](https://gist.github.com/Brottweiler/952c8b0de0afc01c6c8ef18b5a1a5294)

:rofl:

**Comment by CleanMachine1** [comment]
./update: line 166: upd_upd_script: command not found

Welcome to Crilum's Update Script!
Last metadata expiration check: 0:16:24 ago
Dependencies resolved.
Nothing to do.
Complete!

I feared that it would try to mess about with Pi-Apps so I removed everything but what was needed.
