### ISSUE TITLE
Add a makefile to the project

### ISSUE THREAD

**Issue by CleanMachine1** [Crilum/update#12]
Makefiles allow for easy commands to be run for installing, uninstalling and other parts building.

See https://github.com/CleanMachine1/DollarSkip/blob/master/Makefile

It doesn't have to have all the variables and for example

Having

install:
cp update /usr/local/bin/

Would be sufficient for a makefile.

**Comment by Crilum** [comment]
Oh wow, I just realized I only have a Debian install script, and a macOS install script, limiting users to only Debian or macOS! obviously one could just install manually, but.. a better way does need to be created.

I don't know about a makefile, it seems a little excessive for just copying the script...

I think I'll just make a unified install script, that can detect what OS you're using, and install based on that.

**Comment by CleanMachine1** [comment]
Its often used in compiled projects to compile then move binaries to the correct location.

Maybe a unified script and makefile if possible.

**Comment by Crilum** [comment]
>Its often used in compiled projects to compile then move binaries to the correct location.

This project isn't compiled, so I don't really see the need for a makefile. It's useful for projects that need a lot of commands to install (like building compiled programs), but for just copying a simple bash script, I just don't see that it's really the best way.

**Comment by Crilum** [comment]
@CleanMachine1 Sorry I haven't written a install script, I've been busy on [another project](https://github.com/Crilum/websh)..

**Comment by CleanMachine1** [comment]
No its all good!
