### ISSUE TITLE
`rpm` package conflicts with `filesystem-3.16-2.fc36.x86_64`

### ISSUE THREAD

**Issue by AntonVanAssche** [Crilum/update#16]
**Describe the bug**
When I try to install `update` using the provided `rpm` file on the releases page, I get the following error.

```
$ doas dnf install ./update-1.4.1-2.noarch.rpm 
Last metadata expiration check: 0:02:01 ago on Tue Jun 28 21:24:21 2022.
Dependencies resolved.
==========================================================================================================================
 Package                    Architecture               Version                     Repository                        Size
==========================================================================================================================
Installing:
 update                     noarch                     1.4.0-2                     @commandline                      11 k

Transaction Summary
==========================================================================================================================
Install  1 Package

Total size: 11 k
Installed size: 14 k
Is this ok [Y/n]: 
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/bin from install of update-1.4.0-2.noarch conflicts with file from package filesystem-3.16-2.fc36.x86_64
```

**To Reproduce**
1. `wget https://github.com/Crilum/update/releases/download/v1.4.1/update-1.4.1-2.noarch.rpm`
2. `doas dnf install ./update-1.4.1-2.noarch.rpm` (you can also use `sudo`)

**Expected behavior**
`doas dnf install ./update-1.4.1-2.noarch.rpm` installs `update` without any issues.

**Desktop (please complete the following information):**
 - OS: Fedora Linux (36)
 - Version v1.4.1

**Additional context**
I suspect the method for packaging the program for DNF based distributions isn't quite right.

**Comment by Crilum** [comment]
>I suspect the method for packaging the program for DNF based distributions isn't quite right.

Yeah... I just used alien, a tool that converts `.deb`s to `.rpm`s, but it doesn't work flawlessly...

Should I just revert the install script to install `update` manually? I don't really want to setup an actual rpm build, because the spec files are sooo complicated... If you'd like to make a PR to add all the config files for an actual rpm build, I could change the GH Action to build real `.rpm`s...

**Comment by AntonVanAssche** [comment]
> I don't really want to setup an actual rpm build, because the spec files are sooo complicated... If you'd like to make a PR to add all the config files for an actual rpm build, I could change the GH Action to build real `.rpm`s...

It's been a while since I've made a `.rpm` file, so I would have to look it up again. But I could try to make one, once I have a working `.rpm` file I will let you know and open a PR. If you want, could you assign this issue to me, so I can remember it?

> Should I just revert the install script to install update manually?

You could do this for now until there is a working `rpm` file.

**Comment by Crilum** [comment]
> If you want, could you assign this issue to me, so I can remember it?


Done.

> > Should I just revert the install script to install update manually?
> 
> You could do this for now until there is a working `rpm` file.

Done.
