### ISSUE TITLE
PI-apps error when running update all

### ISSUE THREAD

**Issue by craigevil** [Crilum/update#3]
Pi-Apps output:
/home/pi/Downloads/update/update: line 63: /root/pi-apps/updater: No such file or directory

Distro: Raspberry Pi OS  base: Debian GNU/Linux bookworm/sid
Host: Raspberry Pi 400 Rev 1.0 
Kernel: 5.15.4-v8+ 
Shell: bash 5.1.8

**Comment by Crilum** [comment]
I can reproduce this by using `sudo`. Are you using `sudo`? `update` is just meant to be used as a non-root user, but I think I can fix this by using the `$HOME` variable, instead of the `~` character there now. :+1: 
I'll also add a line in the help that explains that `update` is not meant to be used with `sudo`. :smile: 

With sudo:

```
$ sudo update pi-apps

Welcome to Crilum's Update Script!

Pi-Apps output:
/usr/local/bin/update: line 82: /root/pi-apps/updater: No such file or directory

Done!

```

Without sudo:

```
$ update pi-apps

Welcome to Crilum's Update Script!

Pi-Apps output:

Updater mode: cli-yes

Checking for online changes... Done
Scanning apps... Done
Scanning files... Done

Nothing is updatable.

Done!
```

**Comment by Crilum** [comment]
Sorry, somehow I missed that your problem is with the `all` argument.. :man_facepalming: 
The same concept applies though.

**Comment by Crilum** [comment]
Okay, so, figuring this out is going to be a little harder then I thought it would.. When you run `echo $HOME` as root, it echos `/root`. I'm not sure how to do this in a way that won't break use for users that don't have the username `pi`.

**Comment by Crilum** [comment]
@craigevil I updated the `help` arg output to be a little more clear on how to use update. Does using update as a normal user fix your problem?

**Comment by craigevil** [comment]
Sorry, all good without sudo.
